# Generated by Django 4.0.4 on 2022-06-01 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('date_time', models.DateTimeField()),
                ('link', models.URLField()),
                ('image', models.URLField()),
                ('sources', models.JSONField(default=list)),
                ('relevancy', models.IntegerField(default=0)),
            ],
        ),
    ]
